name: agentMet4FoF
channels:
    - conda-forge
dependencies:
    - python >= 3
    - ipykernel
    - numpy
    - scikit-learn
    - scikit-multiflow
    - scipy
    - matplotlib
    - pandas
    - seaborn
    # pip dependencies have to be provided in `requirements.txt` syntax
    - pip:
        - osbrain
