name: agentMET4FOF
channels:
    - defaults
    - conda-forge
dependencies:
    - python >=3.6
    # pip dependencies have to be provided in `requirements.txt` syntax
    - pip:
        - -r requirements.txt
