name: Met4FoF_Code
channels:
    - defaults
dependencies:
    - python = 3.8.2
    - numpy
    # pip dependencies have to be provided in `requirements.txt` syntax
    - pip:
        - -r dev-requirements.txt
        - -r requirements.txt

