name: agentMET4FOF_ml
channels:
    - defaults
dependencies:
    - python = 3.8
    - pip
    # pip dependencies have to be provided in `requirements.txt` syntax
    - pip:
        - -r requirements.txt
