name: agentMET4FOF
channels:
    - defaults
dependencies:
    - python = 3.11
    - pip
    # pip dependencies have to be provided in `requirements.txt` syntax
    - pip:
        - -e .[tutorials]
        - -r requirements.txt
        - -r dev-requirements.txt
