name: Met4FoF_Code
channels:
    - defaults
    - conda-forge
dependencies:
    - python = 3.8
    - pip
    - numpy
    - scipy
    - uncertainties
    # pip dependencies have to be provided in `requirements.txt` syntax
    - pip:
        - -r requirements.txt

