name: met4fof_
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.1.0
  - absl-py=0.9.0
  - alabaster=0.7.12
  - asn1crypto=1.3.0
  - astor=0.8.0
  - astroid=2.3.3
  - babel=2.8.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - cftime=1.1.1.1
  - chardet=3.0.4
  - cmake=3.14.0
  - cryptography=2.8
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - curl=7.69.1
  - cycler=0.10.0
  - cython=0.29.13
  - docutils=0.16
  - freetype=2.9.1
  - gast=0.3.3
  - git=2.20.1
  - graphviz=2.38
  - grpcio=1.27.2
  - h5py=2.10.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.9
  - imagesize=1.2.0
  - intel-openmp=2019.4
  - isort=4.3.21
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg=9b
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.1.0
  - krb5=1.17.1
  - lazy-object-proxy=1.4.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.69.1
  - libgpuarray=0.7.6
  - libnetcdf=4.7.3
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - libpython=2.1
  - libssh2=1.9.0
  - m2w64-binutils=2.25.1
  - m2w64-bzip2=1.0.6
  - m2w64-crt-git=5.0.0.4636.2595836
  - m2w64-gcc=5.3.0
  - m2w64-gcc-ada=5.3.0
  - m2w64-gcc-fortran=5.3.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gcc-objc=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-headers-git=5.0.0.4636.c0ad18a
  - m2w64-isl=0.16.1
  - m2w64-libiconv=1.14
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-make=4.1.2351.a80a8b8
  - m2w64-mpc=1.0.3
  - m2w64-mpfr=3.1.4
  - m2w64-pkg-config=0.29.1
  - m2w64-toolchain=5.3.0
  - m2w64-tools-git=5.0.0.4592.90b8472
  - m2w64-windows-default-manifest=6.4
  - m2w64-winpthreads-git=5.0.0.4634.697f757
  - m2w64-zlib=1.2.8
  - mako=1.1.0
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mccabe=0.6.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - msys2-conda-epoch=20160418
  - nose=1.3.7
  - numpy=1.16.5
  - numpy-base=1.16.5
  - openssl=1.1.1g
  - packaging=20.3
  - pandas=1.0.3
  - patsy=0.5.1
  - pip=20.0.2
  - protobuf=3.11.4
  - pycparser=2.20
  - pygments=2.6.1
  - pygpu=0.7.6
  - pylint=2.4.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyreadline=2.1
  - pysocks=1.7.1
  - python=3.7.4
  - python-dateutil=2.8.1
  - python-graphviz=0.13.2
  - python_abi=3.7
  - pytz=2019.3
  - qt=5.9.7
  - requests=2.23.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - seaborn=0.9.0
  - setuptools=46.1.3
  - sip=4.19.8
  - six=1.14.0
  - snowballstemmer=2.0.0
  - sphinx=2.2.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.31.1
  - statsmodels=0.11.0
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - tensorflow-gpu=1.14.0
  - termcolor=1.1.0
  - theano=1.0.4
  - tk=8.6.8
  - tornado=6.0.4
  - urllib3=1.25.8
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - vs2015_win-64=14.0.25420
  - werkzeug=1.0.1
  - wheel=0.34.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - wrapt=1.12.1
  - xarray=0.15.0
  - zlib=1.2.11
  - pip:
    - arviz==0.9.0
    - attrs==19.3.0
    - backcall==0.1.0
    - beautifulsoup4==4.8.2
    - bleach==3.1.0
    - bs4==0.0.1
    - colorama==0.4.1
    - decorator==4.4.0
    - defusedxml==0.6.0
    - entrypoints==0.3
    - fastprogress==0.2.3
    - importlib-metadata==0.23
    - ipykernel==5.1.2
    - ipyparallel==6.2.4
    - ipython==7.8.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.15.1
    - jsonschema==3.1.1
    - jupyter-client==5.3.4
    - jupyter-core==4.6.0
    - lxml==4.5.0
    - mistune==0.8.4
    - more-itertools==7.2.0
    - nbconvert==5.6.0
    - nbformat==4.4.0
    - netcdf4==1.5.2
    - nltk==3.4.5
    - notebook==6.0.1
    - pandocfilters==1.4.2
    - parso==0.5.1
    - pickleshare==0.7.5
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.10
    - psutil==5.6.3
    - pymc3==3.9.2
    - pyrsistent==0.15.4
    - pywavelets==1.1.1
    - pywin32==225
    - pywinpty==0.5.5
    - pyzmq==18.1.0
    - qtconsole==4.5.5
    - scikit-rvm==0.1.0a1
    - send2trash==1.5.0
    - sklearn==0.0
    - soupsieve==2.0
    - terminado==0.8.2
    - testpath==0.4.2
    - tqdm==4.47.0
    - traitlets==4.3.3
    - typing-extensions==3.7.4.2
    - urlopen==1.0.0
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - wfdb==2.2.1
    - wget==3.2
    - widgetsnbextension==3.5.1
    - zipp==0.6.0

