# CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

executors:
  tester:
    working_directory: ~/repo
    docker:
      - image: cimg/python:3.8
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
  publisher:
    working_directory: ~/repo
    docker:
      - image: cimg/python:3.8
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
  gh_releaser:
    working_directory: ~/repo
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD

workflows:

  pull_subtrees:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ "Pull subtrees", << pipeline.schedule.name >> ]
    jobs:
      - pull_subtrees:
          new_branch: most_recent_subtree_pulls
          context:
            - Docker pulls
      - commit_push_open_pr:
          requires:
            - pull_subtrees
          context:
            - Docker pulls
            - GitHub pushes to BjoernLudwigPTB's public_repos

  nightly_test:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ "Weekly nightly tests", << pipeline.schedule.name >> ]
    jobs:
      - test_PyDynamic:
          context:
            - Docker pulls
      - test_agentMET4FOF:
          context:
            - Docker pulls
      - test_agentMET4FOF_anomaly_detection:
          context:
            - Docker pulls
      - test_time-series-buffer:
          context:
            - Docker pulls
      - test_time-series-metadata:
          context:
            - Docker pulls
      - test_agentMET4FOF_sensors:
          context:
            - Docker pulls
      - test_Met4FoF-redundancy:
          context:
            - Docker pulls

  build_and_test_virtual_environments:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - test_PyDynamic:
          context:
            - Docker pulls
      - test_agentMET4FOF:
          context:
            - Docker pulls
      - test_agentMET4FOF_anomaly_detection:
          context:
            - Docker pulls
      - test_time-series-buffer:
          context:
            - Docker pulls
      - test_time-series-metadata:
          context:
            - Docker pulls
      - test_agentMET4FOF_sensors:
          context:
            - Docker pulls
      - test_Met4FoF-redundancy:
          context:
            - Docker pulls
      - preview_release:
          # Test the 'release' job to avoid trouble when Pull Requests get merged and
          # to preview publishing actions and the new changelog.
          requires:
              - test_PyDynamic
              - test_agentMET4FOF
              - test_agentMET4FOF_anomaly_detection
              - test_time-series-buffer
              - test_time-series-metadata
              - test_agentMET4FOF_sensors
              - test_Met4FoF-redundancy
      - confirm_previewed_release_actions:
          # This job allows for checking that the release we will create in the
          # next step actually is the desired release, by observing the result of
          # preview_release.
          type: approval
          requires:
            - preview_release
          filters:
            branches:
              # This assures the job only being triggered on branch main.
              only: /main/
      - release:
          # Job to potentially create a release based on python-semantic-release's
          # decision and publish it on GitHub and Zenodo. This requires manual
          # approval in the previous step, which is only triggered on branch main,
          # thus this job here is triggered only on main as well.
          context:
            - GitHub pushes to BjoernLudwigPTB's public_repos
          requires:
            - confirm_previewed_release_actions


commands:
  create_result_folder:
    description: "Create test-result folder."
    parameters:
      subfolder:
        type: string
        default: ""
    steps:
    # Create test-result folder.
    - run:
        name: Create test result folder
        command: |
          mkdir -p test-results/<< parameters.subfolder >>

  run_conda_tests:
    description: "Run and store test results."
    parameters:
      subtree:
        type: string
        default: ""
    steps:
    # Run tests! We use pytest's test-runner.
    - run:
        name: Run tests
        command: |
          source $HOME/conda/etc/profile.d/conda.sh
          conda activate Met4FoF_Code
          pytest -v --junitxml=test-results/junit.xml \
          << parameters.subtree >> | tee test-results/pytest.log

    - store_test_artifacts_and_results:
        subtree: << parameters.subtree >>

  run_venv_tests:
    description: "Run and store test results."
    parameters:
      subtree:
        type: string
        default: ""
    steps:
    - run:
        name: Run tests
        command: |
          python -m pytest -v --junitxml=test-results/junit.xml \
            << parameters.subtree >> | tee test-results/pytest.log

    - store_test_artifacts_and_results:
        subtree: << parameters.subtree >>

  store_test_artifacts_and_results:
    description: "Store test results."
    parameters:
      subtree:
        type: string
        default: ""
    steps:
    # Store test results.
    - store_artifacts:
        path: test-results
        destination: test-results/<< parameters.subtree >>

    - store_test_results:
        path: test-results

  subtree_pull:
    description: "Check for any changes."
    parameters:
      subtree:
        type: string
        default: ""
      upstream_url:
        type: string
        default: ""
      branch:
        type: string
        default: ""
    steps:
    - run:
        command: |
          git subtree pull -q --prefix << parameters.subtree >> \
            << parameters.upstream_url >> << parameters.branch >> \
            -m "Update $(echo << parameters.subtree >> | sed -e "s|tutorials/||") 
            to most recent version"

  check_for_new_subtrees:
    description: "Check for any changes."
    steps:
    - run:
        name: Abort if nothing new was pulled
        command: |
          set +e
          git diff main | grep diff
          if [ $? -ne 0 ]; then
              set -e
              echo "No updated subtrees. Nothing to test and commit. We are all 
                good."
              circleci-agent step halt
          fi

  set_git_user_name_and_email:
    description: "Configure git to be commit-ready."
    steps:
    - run:
        name: Set Git user.name and user.email
        command: |
            echo 'git config user.name "Bjoern Ludwig (via CircleCI)"' >> $BASH_ENV
            echo 'git config --global user.email "bjoern.ludwig@ptb.de"' >> $BASH_ENV

jobs:

  pull_subtrees:
    parameters:
      new_branch:
        type: string
    executor:
      name: gh_releaser

    steps:
      - add_ssh_keys:
          fingerprints:
            - "41:e2:e1:e7:a9:a3:8d:62:d9:19:6f:71:fe:f6:20:c1"
      - checkout
      - set_git_user_name_and_email
      - run: git checkout -b << parameters.new_branch >>
      - subtree_pull:
          subtree: agentMET4FOF
          upstream_url: git@github.com:Met4FoF/agentMET4FOF.git
          branch: develop
      - subtree_pull:
          subtree: datareceiver
          upstream_url: git@github.com:Met4FoF/datareceiver.git
          branch: master
      - subtree_pull:
          subtree: Met4FoF-redundancy
          upstream_url: git@github.com:Met4FoF/Met4FoF-redundancy.git
          branch: master
      - subtree_pull:
          subtree: Met4FoF-SmartUpUnit
          upstream_url: git@github.com:Met4FoF/Met4FoF-SmartUpUnit.git
          branch: SSU_V3
      - subtree_pull:
          subtree: PyDynamic
          upstream_url: git@github.com:PTB-M4D/PyDynamic.git
          branch: main
      - subtree_pull:
          subtree: PySensorNetwork
          upstream_url: git@github.com:Met4FoF/PySensorNetwork.git
          branch: master
      - subtree_pull:
          subtree: time-series-buffer
          upstream_url: git@github.com:PTB-M4D/time-series-buffer.git
          branch: master
      - subtree_pull:
          subtree: time-series-metadata
          upstream_url: git@github.com:PTB-M4D/time-series-metadata.git
          branch: main
      - subtree_pull:
          subtree: tutorials/agentMET4FOF_anomaly_detection
          upstream_url: git@github.com:Met4FoF/agentMET4FOF_anomaly_detection.git
          branch: master
      - subtree_pull:
          subtree: tutorials/agentMET4FOF_bayesian_neural_network_ZeMA
          upstream_url: git@github.com:Met4FoF/agentMET4FOF_bayesian_neural_network_ZeMA.git
          branch: master
      - subtree_pull:
          subtree: tutorials/agentMET4FOF_ml
          upstream_url: git@github.com:Met4FoF/agentMET4FOF_ml.git
          branch: main
      - subtree_pull:
          subtree: tutorials/agentMET4FOF_sensors
          upstream_url: git@github.com:Met4FoF/agentMET4FOF_sensors.git
          branch: master
      - subtree_pull:
          subtree: tutorials/agentMET4FOF_ZeMA_emc
          upstream_url: git@github.com:Met4FoF/agentMET4FOF_ZeMA_emc.git
          branch: master
      - subtree_pull:
          subtree: tutorials/connect-agentMET4FOF-smartupunit
          upstream_url: git@github.com:Met4FoF/connect-agentMET4FOF-smartupunit.git
          branch: master
      - subtree_pull:
          subtree: tutorials/PyDynamic_tutorials
          upstream_url: git@github.com:PTB-M4D/PyDynamic_tutorials.git
          branch: main
      - subtree_pull:
          subtree: tutorials/Strathcylde_AFRC_machine_learning_tutorials
          upstream_url: git@github.com:harislulic/Strathcylde_AFRC_machine_learning_tutorials.git
          branch: master
      - subtree_pull:
          subtree: tutorials/ZeMA-machine-learning-tutorials
          upstream_url: git@github.com:harislulic/ZeMA-machine-learning-tutorials.git
          branch: master
      - subtree_pull:
          subtree: ZeMA_testbed_Bayesian_machine_learning
          upstream_url: git@github.com:Met4FoF/ZeMA_testbed_Bayesian_machine_learning.git
          branch: main
      - run:
          name: Abort if no new commit was added
          command: |
            if [ $(git rev-parse HEAD) == ${CIRCLE_SHA1} ]; then
                circleci-agent step halt
            fi
      - run: git push -fu origin << parameters.new_branch >>

  commit_push_open_pr:
    executor:
      name: gh_releaser

    steps:
      - add_ssh_keys:
          fingerprints:
            - "41:e2:e1:e7:a9:a3:8d:62:d9:19:6f:71:fe:f6:20:c1"
      - checkout
      - attach_workspace:
          at: .
      - check_for_new_subtrees
      - set_git_user_name_and_email
      - run: echo 'export NEW_BRANCH=most_recent_subtree_pulls' >> $BASH_ENV
      - run: git checkout -b ${NEW_BRANCH}
      - run:
          name: Install GitHub CLI
          command: |
            curl -fsSL \
              https://cli.github.com/packages/githubcli-archive-keyring.gpg |\
              sudo dd of=/etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) \
              signed-by=/etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg]\
              https://cli.github.com/packages stable main" | \
              sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh
      - run:
          name: Check for an existing PR or create one
          command: |
            set +e
            gh pr list --head=$NEW_BRANCH | grep $NEW_BRANCH
            if [ $? -eq 1 ]; then
                set -e
                gh pr create --base=main --title "Update subtrees" \
                  --body "This PR provides freshly pulled package \
                  versions. It was opened after all subtrees were \
                  successfully updated. If all tests pass with the \
                  new versions, it should be merged as soon as possible to \
                  avoid any security issues due to outdated dependencies."
            else
                set -e
                echo "There already was a PR opened earlier. The 
                  current changes were used to update the existing branch."
            fi

  test_PyDynamic:
    executor: tester

    parallelism: 16

    # Specify the steps to execute during this test jobs.
    steps:
      - checkout
      - create_result_folder

      # Install dependencies and Codecov reporter if necessary.
      - run:
          name: Install dependencies
          command: |
            cd PyDynamic
            python -m pip install --upgrade pip pip-tools
            python -m piptools sync requirements/requirements-py38.txt \
                requirements/dev-requirements-py38.txt

      # Run tests! We use pytest's test-runner.
      - run:
          name: Run tests
          no_output_timeout: 60m
          command: |
            cd PyDynamic
            TEST_FILES=$(circleci tests glob "test/**/test_*.py" | \
              circleci tests split --split-by=timings)
            python -m pytest -v \
              --junitxml=$CIRCLE_WORKING_DIRECTORY/test-results/junit.xml $TEST_FILES

      - store_artifacts:
          path: test-results
          destination: test-results

      - store_test_results:
          path: test-results

  test_agentMET4FOF:
    executor: tester

    steps:
      - checkout
      - create_result_folder:
          subfolder: agentMET4FOF

      # Install dependencies and Codecov reporter if necessary.
      - run:
         name: Install dependencies
         command: |
           python -m pip install --upgrade pip -r agentMET4FOF/requirements.txt \
             -r agentMET4FOF/dev-requirements.txt

      # Run tests! We use pytest's test-runner.
      - run_venv_tests:
          subtree: agentMET4FOF

  test_agentMET4FOF_anomaly_detection:
    executor: tester

    steps:
      - checkout
      - create_result_folder:
          subfolder: tutorials/agentMET4FOF_anomaly_detection

      # Install dependencies and Codecov reporter if necessary.
      - run:
         name: Install dependencies
         command: |
           python -m pip install --upgrade pip setuptools pip-tools numpy
           python -m piptools sync \
             tutorials/agentMET4FOF_anomaly_detection/dev-requirements.txt \
             tutorials/agentMET4FOF_anomaly_detection/requirements.txt

      # Run tests! We use pytest's test-runner.
      - run_venv_tests:
          subtree: tutorials/agentMET4FOF_anomaly_detection

  test_agentMET4FOF_sensors:
    executor: tester

    steps:
      - checkout
      - create_result_folder:
          subfolder: tutorials/agentMET4FOF_sensors

      # Install dependencies. Suddenly since 2021-08-27 we observed an error with
      # previously successful configurations. That is why we introduced the gcc flag
      # as proposed by https://forum.manjaro.org/t/pip-install-rpi-gpio-fail/25788.
      - run:
         name: Install dependencies
         command: |
           python -m pip install --upgrade pip pip-tools
           CFLAGS="-fcommon" python -m piptools sync \
             tutorials/agentMET4FOF_sensors/requirements.txt
           python -m pip install --upgrade pytest

      # Run tests! We use pytest's test-runner.
      - run_venv_tests:
          subtree: tutorials/agentMET4FOF_sensors

  test_time-series-buffer:
    executor: tester

    steps:
      - checkout
      - create_result_folder:
          subfolder: time-series-buffer

      # Create folder for test results.
      - run:
          name: Create test result folder
          command: |
            mkdir test-reports

      # Install dependencies and Codecov reporter if necessary.
      - run:
         name: Install dependencies
         command: |
           python -m pip install --upgrade pip pytest
           python -m pip install -r time-series-buffer/requirements.txt

      # Run tests! We use pytest's test-runner.
      - run_venv_tests:
          subtree: time-series-buffer

  test_time-series-metadata:
    executor: tester

    steps:
      - checkout
      - create_result_folder:
          subfolder: time-series-metadata

      # Create folder for test results.
      - run:
          name: Create test result folder
          command: |
            mkdir test-reports

      # Install dependencies and Codecov reporter if necessary.
      - run:
         name: Install dependencies
         command: |
           python -m pip install --upgrade pip pip-tools
           python -m pip install time-series-metadata/.
           python -m piptools sync \
             time-series-metadata/requirements/dev-requirements-py38.txt

      # Run tests! We use pytest's test-runner.
      - run_venv_tests:
          subtree: time-series-metadata

  test_Met4FoF-redundancy:
    executor: tester

    steps:
      - checkout
      - create_result_folder:
          subfolder: Met4FoF-redundancy

      # Install dependencies and Codecov reporter if necessary.
      - run:
         name: Install dependencies
         command: |
           python -m pip install --upgrade pip \
             -r Met4FoF-redundancy/requirements/requirements.txt \
             -r Met4FoF-redundancy/requirements/dev-requirements.txt

      # Run tests! We use pytest's test-runner.
      - run_venv_tests:
          subtree: Met4FoF-redundancy

  release:
    executor: publisher

    steps:
      # Checkout code.
      - checkout

      # Install dependencies.
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip pip-tools
            python -m piptools sync dev-requirements.txt

      # Publish it, if there is anything to publish!
      - run:
          name: Run semantic-release publish
          command: |
            git config --global user.name "semantic-release (via CircleCI)"
            git config --global user.email "bjoern.ludwig@ptb.de"
            python -m semantic_release publish


  preview_release:
    executor: publisher

    steps:
      # Checkout code.
      - checkout

      # Install dependencies.
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip pip-tools
            python -m piptools sync dev-requirements.txt

      # Fake publish, just to make sure everything works after merging a PR and
      # before actual release jos run.
      - run:
          name: Preview python-semantic-release actions
          command: |
            unset CIRCLE_PULL_REQUEST CIRCLE_PULL_REQUESTS CI_PULL_REQUEST \
              CI_PULL_REQUESTS
            export CIRCLE_BRANCH=main
            git config --global user.name "semantic-release (via CircleCI)"
            git config --global user.email "bjoern.ludwig@ptb.de"
            echo "The changelog of the next release will contain:"
            python -m semantic_release --unreleased changelog
            echo "The output of 'semantic-release --noop publish' is:"
            python -m semantic_release --noop publish
