# CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

executors:
  tester:
    docker:
      - image: circleci/python:3.8.2
  publisher:
    docker:
      - image: circleci/python:3.8

workflows:
  build_and_test_virtual_environments:
    jobs:
      - build_and_test_conda_env
      - build_and_test_venv_env
      - test_PyDynamic
      - test_agentMET4FOF
      - semantic-release:
          # Create 'release' job to create a release and publish it on GitHub and
          # Zenodo.
          requires:
              - build_and_test_conda_env
              - build_and_test_venv_env
              - test_PyDynamic
              - test_agentMET4FOF
          filters:
              branches:
                # This assures the job only being triggered on branch master.
                only: /master/

jobs:
  build_and_test_conda_env:
    executor: tester

    working_directory: ~/repo

    steps:
      # Checkout code.
      - checkout
      # Initialize submodules.
      - run:
          name: Initialize submodules
          command: |
            git submodule sync
            git submodule update --init --recursive

      # Create folder for test results.
      - run:
          name: Create test result folder
          command: |
            mkdir test-reports

      # Install Miniconda.
      - run:
          name: Install Miniconda
          command: |
            wget "https://repo.anaconda.com/miniconda/\
            Miniconda3-latest-Linux-x86_64.sh" -O /home/circleci/miniconda.sh
            mkdir -p /home/circleci/.conda
            bash /home/circleci/miniconda.sh -b -p /home/circleci/conda
            echo 'export PATH=/home/circleci/conda/bin:$PATH' >> $BASH_ENV

      # Download and cache dependencies.
      - restore_cache:
          keys:
            # Specify the unique identifier for the cache.
            - conda-dependencies-{{ checksum "environment.yml" }}
                {{ checksum "requirements.txt" }}
            # Fallback to using the latest cache if no exact match is found.
            - conda-dependencies-

      # Create environment.
      - run:
          name: Create environment
          command: |
            conda update -n base -c defaults conda
            if [ -d "/home/circleci/conda/envs/" ]; then
                conda env update --prune --file environment.yml
            else
                conda env create -f environment.yml
            fi

      - save_cache:
          paths:
            - /home/circleci/conda/envs/
          key: >-
            conda-dependencies-{{ checksum "environment.yml" }} {{ checksum "requirements.txt" }}

      # Run tests! We use pytest's test-runner.
      - run:
          name: Run tests
          command: |
            source activate Met4FoF_Code
            pytest -v --junitxml=test-reports/junit.xml \
            --ignore-glob=**/**/tests/ \
            --ignore=Met4FoF-SmartUpUnit/tools/hv_plotting_test.py \
            --ignore=agentMET4FOF_ZeMA_emc/ \
            > test-reports/pytest.log

      # Store test results.
      - store_artifacts:
          path: test-reports
          destination: test-reports

      - store_test_results:
          path: test-reports

  build_and_test_venv_env:
    executor: tester

    working_directory: ~/repo

    steps:
      # Checkout code.
      - checkout
      # Initialize submodules.
      - run:
          name: Initialize submodules
          command: |
            git submodule sync
            git submodule update --init --recursive

      # Create folder for test results.
      - run:
          name: Create test result folder
          command: |
            mkdir test-reports

      # Download and cache dependencies.
      - restore_cache:
          keys:
            # Specify the unique identifier for the cache.
            - venv-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}
            # Fallback to using the latest cache if no exact match is found.
            - venv-dependencies-

      # Install dependencies.
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip pip-tools numpy
            pip-sync dev-requirements.txt requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: >-
            venv-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}

      # Run tests! We use pytest's test-runner.
      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            pytest -v --junitxml=test-reports/junit.xml \
            --ignore-glob=**/**/tests/ \
            --ignore=Met4FoF-SmartUpUnit/tools/hv_plotting_test.py \
            --ignore=agentMET4FOF_ZeMA_emc/ \
            > test-reports/pytest.log

      # Store test results.
      - store_artifacts:
          path: test-reports
          destination: test-reports

      - store_test_results:
          path: test-reports

  test_PyDynamic:
    executor: tester

    working_directory: ~/repo

    steps:
      # Checkout code.
      - checkout
      # Update and initialize submodules.
      - run: git submodule sync PyDynamic
      - run: git submodule update --init PyDynamic

      # Create folder for test results.
      - run:
          name: Create test result folder
          command: |
            mkdir test-reports

      # Download and cache dependencies.
      - restore_cache:
          keys:
            # Specify the unique identifier for the cache.
            - v1-dependencies-{{ checksum "PyDynamic/requirements/requirements-py38.txt" }}
            # Fallback to using the latest cache if no exact match is found.
            - v1-dependencies-

      # Install dependencies and Codecov reporter if necessary.
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip pip-tools
            pip-sync PyDynamic/requirements/requirements-py38.txt \
                PyDynamic/requirements/dev-requirements-py38.txt

      - save_cache:
          paths:
            - ./venv
          key: >-
            v1-dependencies-{{ checksum "PyDynamic/requirements/requirements-py38.txt" }}

      # Run tests with coverage report! We use pytest's test-runner.
      - run:
          name: Run PyDynamic tests
          command: |
            source venv/bin/activate
            pytest -v --junitxml=test-reports/junit.xml \
            --cov-config=PyDynamic/.coveragerc --cov=PyDynamic/ \
            PyDynamic/ > test-reports/PyDynamic.log

      # Store test results.
      - store_artifacts:
          path: test-reports
          destination: test-reports/PyDynamic

      - store_test_results:
          path: test-reports

  test_agentMET4FOF:
    executor: tester

    working_directory: ~/repo

    steps:
      # Checkout code.
      - checkout
      # Update and initialize submodules.
      - run: git submodule sync agentMET4FOF
      - run: git submodule update --init agentMET4FOF

      # Create folder for test results.
      - run:
          name: Create test result folder
          command: |
            mkdir test-reports

      # Download and cache dependencies.
      - restore_cache:
          keys:
            # Specify the unique identifier for the cache.
            - v1-dependencies-{{ checksum "agentMET4FOF/requirements.txt" }}
            # Fallback to using the latest cache if no exact match is found.
            - v1-dependencies-

      # Install dependencies and Codecov reporter if necessary.
      - run:
         name: Install dependencies
         command: |
           python3 -m venv venv
           source venv/bin/activate
           pip install --upgrade pip
           pip install numpy
           pip install -r agentMET4FOF/requirements.txt
           pip install pytest pytest-cov

      - save_cache:
          paths:
            - ./venv
          key: >-
            v1-dependencies-{{ checksum "agentMET4FOF/requirements.txt" }}

      # Run tests with coverage report! We use pytest's test-runner.
      - run:
          name: Run agentMET4FOF tests
          command: |
            source venv/bin/activate
            pytest -v --junitxml=test-reports/junit.xml \
            --cov-config=.coveragerc --cov=agentMET4FOF/ \
            agentMET4FOF/ > test-reports/agentMET4FOF.log

      # Store test results.
      - store_artifacts:
         path: test-reports
         destination: test-reports/agentMET4FOF

      - store_test_results:
         path: test-reports

  semantic-release:
    executor: publisher

    working_directory: ~/repo

    steps:
      # Checkout code.
      - checkout

      # Download and cache dependencies.
      - restore_cache:
          keys:
            # Specify the unique identifier for the cache.
            - publisher-dependencies-{{ checksum "dev-requirements.txt" }}

      # Install dependencies.
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip pip-tools
            pip-sync dev-requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: >-
            publisher-dependencies-{{ checksum "dev-requirements.txt" }}

      # Publish it!
      - run:
          name: Run semantic-release publish
          command: |
            source venv/bin/activate
            git config --global user.name "semantic-release (via CircleCI)"
            git config --global user.email "bjoern.ludwig@ptb.de"
            semantic-release publish
