# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

executors:
  # Define a parameterized executor which accepts two parameters to choose the python
  # version which will be used for the docker image and the tox actions.
  venv_tester:
    working_directory: ~/repo
    parameters:
      tag:
        type: string
        default: "3.10"
    docker:
      - image: cimg/python:<< parameters.tag >>
  conda_tester:
    working_directory: ~/repo
    docker:
      - image: cimg/base:2021.04

commands:
  # Reusable command to prepare the environment for testing.
  create_folders:
    description: "Checkout code and prepare test results location."
    steps:
    # Checkout code.
    - checkout
    # Create test-result folder.
    - run:
        name: Create test result folder
        command: |
          mkdir test-results

  # Reusable command to prepare the environment for testing.
  create_venv:
    description: "Prepare virtual environment."
    parameters:
      pyenv:
        type: string
        default: "py310"
    steps:
    # Create PyDynamic_tutorials virtual environment.
    - run:
        name: Create virtual environment
        command: |
          python3 -m venv << parameters.pyenv >>
          source << parameters.pyenv >>/bin/activate
          pip install --upgrade pip setuptools pip-tools

  # Reusable command to install production dependencies.
  install_deps:
    description: "Install dependencies."
    parameters:
      pyenv:
        type: string
        default: "py310"
    steps:

    # Install dependencies.
    - run:
        name: Install dependencies
        command: |
          source << parameters.pyenv >>/bin/activate
          python -m piptools sync requirements/requirements.txt requirements/requirements-dev.txt

  # Reusable command to conduct actual testing.
  execute_nbval:
    description: "Execute pytest with nbval plugin."
    parameters:
      pyenv:
        type: string
    steps:

    # Call pytest with nbval.
    - run:
        name: Perform pytest --nbval testing
        command: |
          source << parameters.pyenv >>/bin/activate
          pytest --nbval --current-env --sanitize-with nbval_sanitization | \
            tee --append test-results/pytest.log

  # Reusable command to store the previously generated test results.
  store_results:
    description: "Store test results and artifacts."

    steps:
    # Store test results.
    - store_artifacts:
        path: test-results
        destination: test-results

    - store_test_results:
        path: test-results

workflows:
  # Create workflow for testing PyDynamic_tutorials.
  test:
    jobs:
      - test:
          name: "test_python37"
          tag: "3.7"
          pyenv: "py37"
      - test:
          name: "test_python38"
          tag: "3.8"
          pyenv: "py38"
      - test:
          name: "test_python39"
          tag: "3.9"
          pyenv: "py39"
      - test:
          name: "test_python310"
          tag: "3.10"
          pyenv: "py310"
      - test_conda310

jobs:

  # Define one 'test' job with parameters to deal with all desired cases and one
  # Anaconda test job. The reason for this is the desire to ensure the following for
  # all supported Python versions referring to the docs: all notebooks are
  # guaranteed to produce the same output as they contain, no matter if run with
  # Python built-in venv or the Anaconda interpreter.
  test:
    # Define all parameters, where 'tag' is used for the docker image and 'pyenv' is
    # the string which is used to identify the current Python version. We reuse
    # this variable basically everywhere we deal with the virtual environment.
    parameters:
      tag:
        type: string
        default: "3.10"
      pyenv:
        type: string
        default: "py310"

    # Specify the executor and hand over the docker image tag parameter.
    executor:
      name: venv_tester
      tag: << parameters.tag >>

    # Specify the steps to execute during this test jobs.
    steps:
      - create_folders
      - create_venv:
          pyenv: << parameters.pyenv >>
      - install_deps:
          pyenv: << parameters.pyenv >>

      # Call pytest with nbval.
      - run:
          name: Perform pytest --nbval testing
          command: |
            source << parameters.pyenv >>/bin/activate
            pytest --nbval --current-env --sanitize-with nbval_sanitization | \
              tee --append test-results/pytest.log

      - store_results

  test_conda310:

    executor: conda_tester

    steps:
      - create_folders
      - run:
          name: Install Miniconda
          command: |
            wget "https://repo.anaconda.com/miniconda/\
            Miniconda3-latest-Linux-x86_64.sh" -O $HOME/miniconda.sh
            mkdir -p $HOME/.conda
            bash $HOME/miniconda.sh -b -p /home/circleci/conda
            source $HOME/conda/etc/profile.d/conda.sh
            hash -r
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            echo 'export PATH=$HOME/conda/bin:$PATH' >> $BASH_ENV

      # Download and cache dependencies.
      - restore_cache:
          keys:
            # Specify the unique identifier for the cache.
            - v2-conda-dependencies-{{ checksum "requirements/environment.yml" }}-{{checksum "requirements/requirements.txt" }}-{{ checksum "requirements/requirements-dev.txt" }}
            # Fallback to using the latest cache if no exact match is found.
            - v2-conda-dependencies-

      # Create environment and install extra_requires dependencies manually.
      - run:
          name: Create or update environment
          command: |
            if [ -d "$HOME/conda/envs/" ]; then
                conda env update --prune --file requirements/environment.yml
            else
                conda env create -f requirements/environment.yml
            fi
            source $HOME/conda/etc/profile.d/conda.sh
            conda activate PyDynamic_tutorials
            pip install -r requirements/requirements-dev.txt

      - save_cache:
          paths:
            - /home/circleci/conda/envs/
          key: >-
            v2-conda-dependencies-{{ checksum "requirements/environment.yml" }}-{{ checksum "requirements/requirements.txt" }}-{{ checksum "requirements/requirements-dev.txt" }}

      # Run tests! We use pytest's test-runner.
      - run:
          name: Run tests
          command: |
            source $HOME/conda/etc/profile.d/conda.sh
            conda activate PyDynamic_tutorials
            pytest --nbval --current-env --sanitize-with nbval_sanitization | \
              tee --append test-results/pytest.log

      - store_results