name: agentMET4FOF_bayesian_neural_network_ZeMA
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7
    - pip
    # pip dependencies have to be provided in `requirements.txt` syntax
    - pip:
        - -r requirements.txt
